### ISSUE TITLE
OSD - Modular TS - bios2Uefi Convert disk to GPT won't work when  started from WinPe

### ISSUE THREAD

**Issue by ersatyle** [winadminsdotorg/SystemCenterConfigMgr#30]
OSD - Modular TS - bios2Uefi Convert disk to GPT won't work when  started from WinPe
as it is the disk is formatted during the first steps of the TS when started from WinPe, thus the mbr2gpt.exe conversion tool won't work and the step will fail 
https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt
Disk Prerequisites (...)
There are at most 3 primary partitions in the MBR partition table
One of the partitions is set as active and is the system partition
The disk does not have any extended/logical partition
The BCD store on the system partition contains a default OS entry pointing to an OS partition

you can add logic for when the TS_type_new is true you format the disk to prepare for conversion with 
TSUEFIDrive variable, reboot and then format again for GPT

![image](https://user-images.githubusercontent.com/21692877/39587470-8c901604-4ec7-11e8-951f-71d93f96984b.png)

**Comment by Ebag333** [comment]
>OSD - Modular TS - bios2Uefi Convert disk to GPT won't work when started from WinPe
>as it is the disk is formatted during the first steps of the TS when started from WinPe

This is by design.  You can't really run a upgrade in place straight from WinPE anyway (have to reboot back to Windows), so there's not much point to doing the conversion steps _unless_ you want to run offline (in place) USMT. And that's a super niche condition: `I can't boot to Windows but I still want to save user data.`

You could easily change the conditions to have that functionality (there's a reason why it's set very high level as it is), and if you DID want to do USMT that would be a requirement.  You'll also notice that USMT is disabled by default.... ;)

I don't see a reason to change it as it's very easy to change yourself for your own environment if desired, and as mentioned most scenarios that it'd be used in is really niche.  This isn't a be-all-end-all solution, it's supposed to get you 90% of the way there and you customize it to fit your environment.

The base assumption of the TS as-is:
- Launch from WinPE (PXE or Bootable Media): New image so we can nuke the disk
- Launch from Windows: Upgrade in place, leave data intact

**Comment by ersatyle** [comment]
I think the point was totally missed, if was not about not formatting the disk at the beginning of the TS in WinPe.
But since the disk is formatted, we can't use the mbr2gpt.exe to simply convert the disk in a bios to UEFI scenario, that simply doesn't work.
We need at this point to format again (not convert) using the TSUEFIDrive variable, reboot, and format one last time in GPT.

**Comment by Ebag333** [comment]
>But since the disk is formatted, we can't use the mbr2gpt.exe to simply convert the disk in a bios to UEFI scenario, that simply doesn't work.

If the disk was formatted as MBR, then `mbr2gpt` will work just fine.

The bios section of the modular TS is by far the weakest.  It's half done, and not really done properly.

**Comment by ersatyle** [comment]
no, if you read the prerequisite for mbr2gpt
"The BCD store on the system partition contains a default OS entry pointing to an OS partition"
since disk was formatted, you don't have this, thus not working (failing in the TS, didn't keep the error sorry.)

**Comment by Ebag333** [comment]
Task sequence redone. This should not be an issue anymore
